In [2]:
# Assignment 2 
# Global Alignment 
# VHLTPEEKSAVTALWG and VAFTEKQEALVSSSLEAF   


SEQUENCE_1 = 'VHLTPEEKSAVTALWG' #Sequence 1 (Side Sequence)
SEQUENCE_2 = 'VAFTEKQEALVSSSLEAF' #Sequence 2 (Top Sequence)
MATRIX_ROW_N = len(SEQUENCE_1)+1 #Initiation Matrix Size (Rows)
MATRIX_COLUMN_N = len(SEQUENCE_2)+1 #Initiation Matrix Size (Columns)
MATCH_SCORE = 1 #Match Score
MISMATCH_SCORE = -1 #Mismatch Score
GAP_SCORE = -2 #Gap Points
GAP_CHARACTER = '-'#Character to Represent Gaps in Final Alignemnts
ALN_PATHWAYS = [] #Initiating List of Discovered aln Pathways
MATRIX = [[[[None] for i in range(2)] for i in range(MATRIX_COLUMN_N)] for i in range(MATRIX_ROW_N)] # Initiating Score Matrix

def print_aln_details(aln): # Function to print steps of particular aln
    print('\n>>>>>>>>>>>>>>>> Aln #:'+str(aln[4])+' <<<<<<<<<<<<<<<<\n\n------------------Steps------------------\n')
    for elem in aln[3]:
        print('Step: '+str(elem[0])+' -> Score = ' + str(elem[1])    + ' -> Dir: ' + ('\u2190' if elem[2]==1 else ('\u2196' if elem[2]==2 else ('\u2191' if elem[2]==3 else 'Error'))))
    print('\n-------------Final aln-------------\n')
    print(aln[1]+'\n'+aln[0])
    return

def print_all(ALIGNMENTS): #Function to print everything
    print('Total Alignments: ' + str(len(ALIGNMENTS)))
    print('Overall Score: '+str(ALIGNMENTS[0][3][0][1])+'\n')
    for elem in ALIGNMENTS:
        print_aln_details(elem)
    return
def print_alns_only(ALIGNMENTS): #Function to print only ALIGNMENTS
    print('Total Alignments: ' + str(len(ALIGNMENTS)))
    print('Overall Score: '+str(ALIGNMENTS[0][3][0][1])+'\n')
    for elem in ALIGNMENTS:
        print(elem[0]+'\n'+elem[1]+'\n')
    return
def find_each_path(c_i,c_j,path=''): #Nested function to discover new aln pathways
    global ALN_PATHWAYS 
    i = c_i 
    j = c_j 
    if i == 0 and j==0: 
        ALN_PATHWAYS.append(path) 
        return 2 
    dir_t = len(MATRIX[i][j][1]) 
    while dir_t<=1: 
        n_dir = MATRIX[i][j][1][0] if (i != 0 and j != 0) else (1 if i == 0 else (3 if j==0 else 0)) 
        path = path + str(n_dir) 
        if n_dir == 1: 
            j=j-1
        elif n_dir == 2:
            i=i-1
            j=j-1
        elif n_dir == 3:
            i=i-1
        dir_t = len(MATRIX[i][j][1])
        if i == 0 and j==0:
            ALN_PATHWAYS.append(path)
            return 3
    if dir_t>1:
        for dir_c in range(dir_t):
            n_dir = MATRIX[i][j][1][dir_c] if (i != 0 and j != 0) else (1 if i == 0 else (3 if j==0 else 0))
            tmp_path = path + str(n_dir)
            if n_dir == 1:
                n_i = i
                n_j=j-1
            elif n_dir == 2:
                n_i=i-1
                n_j=j-1
            elif n_dir == 3:
                n_i=i-1
                n_j = j
            find_each_path(n_i,n_j,tmp_path)
    return len(ALN_PATHWAYS)

#Main Code
#Matrix Evaulation [start]
for i in range(MATRIX_ROW_N):
    MATRIX[i][0] = [GAP_SCORE*i,[]]
for j in range(MATRIX_COLUMN_N):
     MATRIX[0][j] = [GAP_SCORE*j,[]]
for i in range(1,MATRIX_ROW_N):
    for j in range(1,MATRIX_COLUMN_N):
        score = MATCH_SCORE if (SEQUENCE_1[i-1] == SEQUENCE_2[j-1]) else MISMATCH_SCORE
        h_val = MATRIX[i][j-1][0] + GAP_SCORE
        d_val = MATRIX[i-1][j-1][0] + score
        v_val = MATRIX[i-1][j][0] + GAP_SCORE
        o_val = [h_val, d_val, v_val]
        MATRIX[i][j] = [max(o_val), [i+1 for i,v in enumerate(o_val) if v==max(o_val)]] # h = 1, d = 2, v = 3
#Matrix Evaulation [end]
OVERALL_SCORE = MATRIX[i][j][0]
score = OVERALL_SCORE
l_i = i
l_j = j
ALIGNMENTS = []
tot_aln = find_each_path(i,j)
aln_count = 0
#Compiling alignments based on discovered matrix pathways
for elem in ALN_PATHWAYS:
    i = l_i-1
    j = l_j-1
    side_aln = ''
    top_aln = ''
    step = 0
    aln_info = []
    for n_dir_c in range(len(elem)):
        n_dir = elem[n_dir_c]
        score = MATRIX[i+1][j+1][0]
        step = step + 1
        aln_info.append([step,score,n_dir])
        if n_dir == '2':
            side_aln = side_aln + SEQUENCE_1[i]
            top_aln = top_aln + SEQUENCE_2[j]
            i=i-1
            j=j-1
        elif n_dir == '1':
            side_aln = side_aln + GAP_CHARACTER
            top_aln = top_aln + SEQUENCE_2[j]
            j=j-1
        elif n_dir == '3':
            side_aln = side_aln + SEQUENCE_1[i]
            top_aln = top_aln + GAP_CHARACTER
            i=i-1
    aln_count = aln_count + 1
    ALIGNMENTS.append([top_aln[::-1],side_aln[::-1],elem,aln_info,aln_count])

print_alns_only(ALIGNMENTS)

Total Alignments: 9
Overall Score: -11

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VTA-LWG-

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VT-ALWG-

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-V-TALWG-

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VTA-LW-G

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VT-ALW-G

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-V-TALW-G

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VTA-L-WG

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-VT-AL-WG

VAFT-EKQEALVSSSLEAF
VHLTPEEKSA-V-TAL-WG



In [4]:
# Local Alignment 
import itertools
import numpy as np

def matrix(a, b, match_score=3, gap_cost=2):
    H = np.zeros((len(a) + 1, len(b) + 1), int)

    for i, j in itertools.product(range(1, H.shape[0]), range(1, H.shape[1])):
        match = H[i - 1, j - 1] + (match_score if a[i - 1] == b[j - 1] else - match_score)
        delete = H[i - 1, j] - gap_cost
        insert = H[i, j - 1] - gap_cost
        H[i, j] = max(match, delete, insert, 0)
    return H
def traceback(H, b, b_='', old_i=0):
    # flip H to get index of **last** occurrence of H.max() with np.argmax()
    H_flip = np.flip(np.flip(H, 0), 1)
    i_, j_ = np.unravel_index(H_flip.argmax(), H_flip.shape)
    i, j = np.subtract(H.shape, (i_ + 1, j_ + 1))  # (i, j) are **last** indexes of H.max()
    if H[i, j] == 0:
        return b_, j
    b_ = b[j - 1] + '-' + b_ if old_i - i > 1 else b[j - 1] + b_
    return traceback(H[0:i, 0:j], b, b_, i)
def smith_waterman(a, b, match_score=3, gap_cost=2):
    a, b = a.upper(), b.upper()
    H = matrix(a, b, match_score, gap_cost)
    b_, pos = traceback(H, b)
    return pos, pos + len(b_)


In [5]:
# VHLTPEEKSAVTALWG and VAFTEKQEALVSSSLEAF   
print(matrix('VHLTPEEKSAVTALWG', 'VAFTEKQEALVSSSLEAF'))
a, b = 'VHLTPEEKSAVTALWG', 'VAFTEKQEALVSSSLEAF'
H = matrix(a, b)
print(traceback(H, b))
a, b = 'VHLTPEEKSAVTALWG', 'VAFTEKQEALVSSSLEAF'
start, end = smith_waterman(a, b)
print(a[start:end])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 3 1 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 3 1 0 0 0 3 1 0 0]
 [0 0 0 0 3 1 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 4 2 0 3 1 0 0 0 0 0 0 3 1 0]
 [0 0 0 0 0 3 1 0 3 1 0 0 0 0 0 0 3 1 0]
 [0 0 0 0 0 1 6 4 2 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 4 3 1 0 0 0 3 3 3 1 0 0 0]
 [0 0 3 1 0 0 2 1 0 4 2 0 1 1 1 0 0 3 1]
 [0 3 1 0 0 0 0 0 0 2 1 5 3 1 0 0 0 1 0]
 [0 1 0 0 3 1 0 0 0 0 0 3 2 0 0 0 0 0 0]
 [0 0 4 2 1 0 0 0 0 3 1 1 0 0 0 0 0 3 1]
 [0 0 2 1 0 0 0 0 0 1 6 4 2 0 0 3 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 4 3 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0]]
('V-T-E-K-L', 0)
VHLTPEEKS


In [3]:
# Assignment 3 
# Global Alignment
# GTTACTTTGGACCCTCAA and AAATTGATCTTTTAAC
SEQUENCE_1 = 'GTTACTTTGGACCCTCAA' #Sequence 1 (Side Sequence)
SEQUENCE_2 = 'AAATTGATCTTTTAAC' #Sequence 2 (Top Sequence)
MATRIX_ROW_N = len(SEQUENCE_1)+1 #Initiation Matrix Size (Rows)
MATRIX_COLUMN_N = len(SEQUENCE_2)+1 #Initiation Matrix Size (Columns)
MATCH_SCORE = 1 #Match Score
MISMATCH_SCORE = -1 #Mismatch Score
GAP_SCORE = -2 #Gap Points
GAP_CHARACTER = '-'#Character to Represent Gaps in Final Alignemnts
ALN_PATHWAYS = [] #Initiating List of Discovered aln Pathways
MATRIX = [[[[None] for i in range(2)] for i in range(MATRIX_COLUMN_N)] for i in range(MATRIX_ROW_N)] # Initiating Score Matrix

def print_aln_details(aln): # Function to print steps of particular aln
    print('\n>>>>>>>>>>>>>>>> Aln #:'+str(aln[4])+' <<<<<<<<<<<<<<<<\n\n------------------Steps------------------\n')
    for elem in aln[3]:
        print('Step: '+str(elem[0])+' -> Score = ' + str(elem[1])    + ' -> Dir: ' + ('\u2190' if elem[2]==1 else ('\u2196' if elem[2]==2 else ('\u2191' if elem[2]==3 else 'Error'))))
    print('\n-------------Final aln-------------\n')
    print(aln[1]+'\n'+aln[0])
    return

def print_all(ALIGNMENTS): #Function to print everything
    print('Total Alignments: ' + str(len(ALIGNMENTS)))
    print('Overall Score: '+str(ALIGNMENTS[0][3][0][1])+'\n')
    for elem in ALIGNMENTS:
        print_aln_details(elem)
    return
def print_alns_only(ALIGNMENTS): #Function to print only ALIGNMENTS
    print('Total Alignments: ' + str(len(ALIGNMENTS)))
    print('Overall Score: '+str(ALIGNMENTS[0][3][0][1])+'\n')
    for elem in ALIGNMENTS:
        print(elem[0]+'\n'+elem[1]+'\n')
    return
def find_each_path(c_i,c_j,path=''): #Nested function to discover new aln pathways
    global ALN_PATHWAYS 
    i = c_i 
    j = c_j 
    if i == 0 and j==0: 
        ALN_PATHWAYS.append(path) 
        return 2 
    dir_t = len(MATRIX[i][j][1]) 
    while dir_t<=1: 
        n_dir = MATRIX[i][j][1][0] if (i != 0 and j != 0) else (1 if i == 0 else (3 if j==0 else 0)) 
        path = path + str(n_dir) 
        if n_dir == 1: 
            j=j-1
        elif n_dir == 2:
            i=i-1
            j=j-1
        elif n_dir == 3:
            i=i-1
        dir_t = len(MATRIX[i][j][1])
        if i == 0 and j==0:
            ALN_PATHWAYS.append(path)
            return 3
    if dir_t>1:
        for dir_c in range(dir_t):
            n_dir = MATRIX[i][j][1][dir_c] if (i != 0 and j != 0) else (1 if i == 0 else (3 if j==0 else 0))
            tmp_path = path + str(n_dir)
            if n_dir == 1:
                n_i = i
                n_j=j-1
            elif n_dir == 2:
                n_i=i-1
                n_j=j-1
            elif n_dir == 3:
                n_i=i-1
                n_j = j
            find_each_path(n_i,n_j,tmp_path)
    return len(ALN_PATHWAYS)

#Main Code
#Matrix Evaulation [start]
for i in range(MATRIX_ROW_N):
    MATRIX[i][0] = [GAP_SCORE*i,[]]
for j in range(MATRIX_COLUMN_N):
     MATRIX[0][j] = [GAP_SCORE*j,[]]
for i in range(1,MATRIX_ROW_N):
    for j in range(1,MATRIX_COLUMN_N):
        score = MATCH_SCORE if (SEQUENCE_1[i-1] == SEQUENCE_2[j-1]) else MISMATCH_SCORE
        h_val = MATRIX[i][j-1][0] + GAP_SCORE
        d_val = MATRIX[i-1][j-1][0] + score
        v_val = MATRIX[i-1][j][0] + GAP_SCORE
        o_val = [h_val, d_val, v_val]
        MATRIX[i][j] = [max(o_val), [i+1 for i,v in enumerate(o_val) if v==max(o_val)]] # h = 1, d = 2, v = 3
#Matrix Evaulation [end]
OVERALL_SCORE = MATRIX[i][j][0]
score = OVERALL_SCORE
l_i = i
l_j = j
ALIGNMENTS = []
tot_aln = find_each_path(i,j)
aln_count = 0
#Compiling alignments based on discovered matrix pathways
for elem in ALN_PATHWAYS:
    i = l_i-1
    j = l_j-1
    side_aln = ''
    top_aln = ''
    step = 0
    aln_info = []
    for n_dir_c in range(len(elem)):
        n_dir = elem[n_dir_c]
        score = MATRIX[i+1][j+1][0]
        step = step + 1
        aln_info.append([step,score,n_dir])
        if n_dir == '2':
            side_aln = side_aln + SEQUENCE_1[i]
            top_aln = top_aln + SEQUENCE_2[j]
            i=i-1
            j=j-1
        elif n_dir == '1':
            side_aln = side_aln + GAP_CHARACTER
            top_aln = top_aln + SEQUENCE_2[j]
            j=j-1
        elif n_dir == '3':
            side_aln = side_aln + SEQUENCE_1[i]
            top_aln = top_aln + GAP_CHARACTER
            i=i-1
    aln_count = aln_count + 1
    ALIGNMENTS.append([top_aln[::-1],side_aln[::-1],elem,aln_info,aln_count])

print_alns_only(ALIGNMENTS)

Total Alignments: 22
Overall Score: -7

---AAATTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

--AA-ATTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

-A-A-ATTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

A--A-ATTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

--AAA-TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

-A-AA-TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

A--AA-TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

-AAA--TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

A-AA--TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

AA-A--TTGATCTTTTAAC
GTTACTTTGGACCCTCAA-

--AAAT-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

-A-AAT-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

A--AAT-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

-AAA-T-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

A-AA-T-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

AA-A-T-TGATCTTTTAAC
GTTACTTTGGACCCTCAA-

--AAATT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-

-A-AATT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-

A--AATT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-

-AAA-TT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-

A-AA-TT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-

AA-A-TT-GATCTTTTAAC
GTTACTTTGGACCCTCAA-



In [6]:
# Local Alignment 
import itertools
import numpy as np

def matrix(a, b, match_score=3, gap_cost=2):
    H = np.zeros((len(a) + 1, len(b) + 1), int)

    for i, j in itertools.product(range(1, H.shape[0]), range(1, H.shape[1])):
        match = H[i - 1, j - 1] + (match_score if a[i - 1] == b[j - 1] else - match_score)
        delete = H[i - 1, j] - gap_cost
        insert = H[i, j - 1] - gap_cost
        H[i, j] = max(match, delete, insert, 0)
    return H
def traceback(H, b, b_='', old_i=0):
    # flip H to get index of **last** occurrence of H.max() with np.argmax()
    H_flip = np.flip(np.flip(H, 0), 1)
    i_, j_ = np.unravel_index(H_flip.argmax(), H_flip.shape)
    i, j = np.subtract(H.shape, (i_ + 1, j_ + 1))  # (i, j) are **last** indexes of H.max()
    if H[i, j] == 0:
        return b_, j
    b_ = b[j - 1] + '-' + b_ if old_i - i > 1 else b[j - 1] + b_
    return traceback(H[0:i, 0:j], b, b_, i)
def smith_waterman(a, b, match_score=3, gap_cost=2):
    a, b = a.upper(), b.upper()
    H = matrix(a, b, match_score, gap_cost)
    b_, pos = traceback(H, b)
    return pos, pos + len(b_)


In [7]:
# GTTACTTTGGACCCTCAA and AAATTGATCTTTTAAC
print(matrix('GTTACTTTGGACCCTCAA', 'AAATTGATCTTTTAAC'))
a, b = 'GTTACTTTGGACCCTCAA', 'AAATTGATCTTTTAAC'
H = matrix(a, b)
print(traceback(H, b))
a, b = 'GTTACTTTGGACCCTCAA', 'AAATTGATCTTTTAAC'
start, end = smith_waterman(a, b)
print(a[start:end])

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  3  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  3  1  0  4  2  3  3  3  3  1  0  0]
 [ 0  0  0  0  3  6  4  2  3  1  5  6  6  6  4  2  0]
 [ 0  3  3  3  1  4  3  7  5  3  3  4  4  4  9  7  5]
 [ 0  1  1  1  0  2  1  5  4  8  6  4  2  2  7  6 10]
 [ 0  0  0  0  4  3  1  3  8  6 11  9  7  5  5  4  8]
 [ 0  0  0  0  3  7  5  3  6  5  9 14 12 10  8  6  6]
 [ 0  0  0  0  3  6  4  2  6  4  8 12 17 15 13 11  9]
 [ 0  0  0  0  1  4  9  7  5  3  6 10 15 14 12 10  8]
 [ 0  0  0  0  0  2  7  6  4  2  4  8 13 12 11  9  7]
 [ 0  3  3  3  1  0  5 10  8  6  4  6 11 10 15 14 12]
 [ 0  1  1  1  0  0  3  8  7 11  9  7  9  8 13 12 17]
 [ 0  0  0  0  0  0  1  6  5 10  8  6  7  6 11 10 15]
 [ 0  0  0  0  0  0  0  4  3  8  7  5  5  4  9  8 13]
 [ 0  0  0  0  3  3  1  2  7  6 11 10  8  8  7  6 11]
 [ 0  0  0  0  1  1  0  0  5 10  9  8  7  6  5  4  9]
 [ 0  3  3  3  1  0  0  3  3  8  7  6  5  4  9  8  7]
 [ 0  3  6  6  4  2  0  3  1