### IBS-4 ASSIGNMENT
#### NAME:N.SUSHMA
#### REGISTRATION NO: BL.EN.U4AIE20038
### Needleman-wunch Algorithm

In [1]:
import numpy as np
# sequence1 = "ATGCT"
# sequence2 = "AGCT"

sequence1 = "CCGTCG"
sequence2 = "CCGCG"

# Creating matrices
main_matrix = np.zeros((len(sequence1) + 1, len(sequence2) + 1))
match_checker_matrix = np.zeros((len(sequence1), len(sequence2)))

# Providing the score for match, mismatches and gap
match_reward = 1
mismatch_penalty = -1
gap_penalty = -2

# fill the match checker matrix according to match or mismatch
for i in range(len(sequence1)):
    for j in range(len(sequence2)):
        if sequence1[i] == sequence2[j]:
            match_checker_matrix[i][j]=match_reward
        else:
            match_checker_matrix[i][j] = mismatch_penalty
#print(match_checker_matrix)

#filling up the matrix using needleman wunsch algorithhm

#step1: Initialization
for i in range(len(sequence1)+1):
    main_matrix[i][0]=i*gap_penalty
for j in range(len(sequence2)+1):
    main_matrix[0][j]=j*gap_penalty
    
#step2: matrix filling
for i in range(1,len(sequence1)+1):
    for j in range(1,len(sequence2)+1):
        main_matrix[i][j]=max(main_matrix[i-1][j-1]+match_checker_matrix[i-1][j-1],
                              main_matrix[i-1][j]+gap_penalty, main_matrix[i][j-1]+gap_penalty)
print(main_matrix)

#Step3: Traceback
aligned_1=" "
aligned_2=" "
ti=len(sequence1)
tj=len(sequence2)
while(ti>=0 and tj>0):
    if(ti>=0 and tj>0 and main_matrix[ti][tj]==main_matrix[ti-1][tj-1]+match_checker_matrix[ti-1][tj-1]):
        aligned_1=sequence1[ti-1]+aligned_1
        aligned_2=sequence2[tj-1]+aligned_2
        ti=ti-1
        tj=tj-1
    elif(ti>=0 and main_matrix[ti][tj]== main_matrix[ti-1][tj]+ gap_penalty):
        aligned_1=sequence1[ti-1]+aligned_1
        aligned_2 = "_" + aligned_2
        ti=ti-1
    else:
        aligned_1 = "_"+ aligned_1
        aligned_2 = sequence2[tj - 1] + aligned_2
        tj = tj - 1
        
print(aligned_1)
print(aligned_2)

[[  0.  -2.  -4.  -6.  -8. -10.]
 [ -2.   1.  -1.  -3.  -5.  -7.]
 [ -4.  -1.   2.   0.  -2.  -4.]
 [ -6.  -3.   0.   3.   1.  -1.]
 [ -8.  -5.  -2.   1.   2.   0.]
 [-10.  -7.  -4.  -1.   2.   1.]
 [-12.  -9.  -6.  -3.   0.   3.]]
CCGTCG 
CCG_CG 
